# Generated by Django 4.0.1 on 2022-02-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='uploads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
