# Generated by Django 4.0.1 on 2022-02-05 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_plants_options'),
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plants')),
            ],
        ),
    ]
