# Generated by Django 4.0.1 on 2022-02-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_diseases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseases',
            options={'verbose_name_plural': 'Disease'},
        ),
        migrations.CreateModel(
            name='Cure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('diseases', models.ManyToManyField(to='diseases.Diseases')),
            ],
        ),
    ]
