# Generated by Django 4.0.1 on 2022-02-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_alter_diseases_options_cure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploads',
            options={'verbose_name_plural': 'Uploads'},
        ),
        migrations.AddField(
            model_name='diseases',
            name='ml_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
