# Generated by Django 4.0.1 on 2022-02-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0004_alter_uploads_options_diseases_ml_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseases',
            old_name='plant_id',
            new_name='plant',
        ),
    ]
