# Generated by Django 4.0.1 on 2022-02-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0005_rename_plant_id_diseases_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='ml_id',
            field=models.IntegerField(unique=True),
        ),
    ]
