# Generated by Django 4.0.1 on 2022-02-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0007_detectionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionhistory',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
