# Generated by Django 4.0.1 on 2022-03-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0008_detectionhistory_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionhistory',
            name='probability',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
