# Generated by Django 4.0.1 on 2022-02-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plants',
            options={'verbose_name_plural': 'Plants'},
        ),
    ]
