# Generated by Django 4.0.1 on 2022-02-22 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reports_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCorrection', models.BooleanField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cure_name', models.CharField(max_length=50)),
                ('cure_description', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reports')),
            ],
        ),
        migrations.CreateModel(
            name='NewCure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reports')),
            ],
        ),
    ]
