# Generated by Django 4.0.1 on 2022-04-03 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_newcure_options_alter_newdisease_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
    ]
